### PR TITLE
Issue Fix

### PR DESCRIPTION
**Pull request by rish07**
Hey @mannprerak2 
Fixed issues #10 and #9, please let me know your reviews.

### CODE REVIEW

**Comment by mannprerak2** [comment]
HI @rish07,
The issues you are trying to fix actually require implementation changes in android side of this package.
Simply adding an await keyword will not fix these, you require knowledge of android to be able to solve these.

**Comment by rish07** [comment]
Got it @mannprerak2, I'll close this PR and try again.  

Thank you

**Comment by mannprerak2** [comment]
@rish07 Sure, also be sure to test if by running the example on your device. You wouldn't need a second device for testing these

**Comment by Edorin9** [comment]
I'd like to offer help but looks like you want to do it yourself. Good luck on learning :). Good job. Contact me if you need help or want to ask questions on the android side. Looking forward to using this package.

**Comment by mannprerak2** [comment]
@Edorin9 Please feel free to work on this, I am actually a little busy these days.
Unless @rish07 wants to work on this?

**Comment by rish07** [comment]
@mannprerak2 Actually I'm busy with exams rn, so won't be able to contribute as of now.

**Comment by mannprerak2** [comment]
@Edorin9 I guess you can work on these if you would like to 😄 I would be happy to accept contributions

**Comment by Edorin9** [comment]
Ok sure, I'll look into the code on weekends. Cheers!

**Pull request closed without merging**
